# Generated by Django 5.2.7 on 2025-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for custom pricing', max_digits=10, null=True)),
                ('price_description', models.CharField(blank=True, help_text="e.g., 'Starting at', 'Per project', 'Monthly'", max_length=100)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class like 'fas fa-code'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which services appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Upload a high-quality image of your project', upload_to='projects/')),
                ('client_name', models.CharField(blank=True, help_text='Name of the client (optional)', max_length=200)),
                ('project_url', models.URLField(blank=True, help_text='Link to live project (optional)')),
                ('completion_date', models.DateField(blank=True, help_text='When was this project completed?', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project on the homepage')),
                ('order', models.IntegerField(default=0, help_text='Order in which projects appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(help_text='Select services used in this project', related_name='projects', to='core.service')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
