# Generated by Django 5.2.7 on 2025-11-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioimage_testimonial_service_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DevPortfolio', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('default_hero_image', models.ImageField(blank=True, help_text='Default hero image when no portfolio images are available', null=True, upload_to='site/hero/')),
                ('contact_background', models.ImageField(blank=True, help_text='Background image for contact page', null=True, upload_to='site/contact/')),
                ('admin_background', models.ImageField(blank=True, help_text='Background image for admin panel', null=True, upload_to='site/admin/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['category', 'order', '-created_at'], 'verbose_name': 'Portfolio Image', 'verbose_name_plural': 'Portfolio Images'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='project',
            name='additional_images',
            field=models.ManyToManyField(blank=True, help_text='Additional images for project gallery', related_name='project_galleries', to='core.portfolioimage'),
        ),
        migrations.AddField(
            model_name='service',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for service detail page', null=True, upload_to='services/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('services', 'Services Section'), ('projects', 'Projects Section'), ('contact', 'Contact Section'), ('about', 'About Section'), ('background', 'Background Images'), ('pattern', 'Pattern Images'), ('icon', 'Icon Images'), ('testimonial', 'Testimonial Background'), ('cta', 'Call to Action Background'), ('general', 'General Images')], default='general', max_length=20),
        ),
    ]
