# Generated by Django 5.2.7 on 2025-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_alter_portfolioimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('services', 'Services Section'), ('projects', 'Projects Section'), ('contact', 'Contact Section'), ('about', 'About Section'), ('background', 'Background Images'), ('pattern', 'Pattern Images'), ('icon', 'Icon Images'), ('testimonial', 'Testimonial Background'), ('cta', 'Call to Action Background'), ('process', 'Process Section'), ('tech', 'Technology Section'), ('general', 'General Images')], default='general', max_length=20),
        ),
    ]
