# Generated by Django 5.2.7 on 2025-11-08 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_portfolioimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tool', 'Tool'), ('mobile', 'Mobile'), ('cloud', 'Cloud')], default='tool', max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency level from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to GitHub repository (optional)'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this service on the homepage'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('services', 'Services Section'), ('projects', 'Projects Section'), ('contact', 'Contact Section'), ('about', 'About Section'), ('background', 'Background Images'), ('pattern', 'Pattern Images'), ('icon', 'Icon Images'), ('testimonial', 'Testimonial Background'), ('cta', 'Call to Action Background'), ('general', 'General Images')], default='general', max_length=20),
        ),
    ]
